### ISSUE TITLE
a lot of PRs

### ISSUE THREAD

**Issue by fscottfoti** [synthicity/activitysim#12]
As people may have noticed, there are a lot of pull requests right now (more than I would like).  I'd love to start merging the early PRs, but we're waiting on a resolution to the omx issue.  Right now all these PRs depend on the omx that we have within activitysim.  If we want to depend on omx outside of activitysim then we need to make those changes in omx first.  Or alternatively, I suppose we could leave omx in activitysim for now and then remove it once the omx repo is setup so that it can be a dependency of activitysim.  Bottom line is I will start merging PRs if people are ok with omx being in activitysim for now.  Any takers?

**Comment by waddell** [comment]
I thought the resolution on this issue was that Billy would make changes to
omx in its own repository?  Possibly with patches or pull requests from us?

**Comment by fscottfoti** [comment]
That is the resolution.  I wanted to alert everyone that we're waiting to merge these PRs until that is completed - that having this many PRs is not ideal.

**Comment by waddell** [comment]
Got it. Do we need to send a pull request on the omx repo to move this
along?

**Comment by fscottfoti** [comment]
I think we have an open issue there - not sure what the latest is.  @jiffyclub?

**Comment by jiffyclub** [comment]
I opened osPlanning/omx#13 last month, but haven't heard anything.

**Comment by danielsclint** [comment]
Let me try to connect with @billyc and @bstabler directly today. I would prefer to try and keep these two library separate in order to avoid many of the current issues that plagued the PB-Commons library over the years. However, if we don't get a commitment by tomorrow to make adjustments to OMX, I would be fine with having a copy here *FOR NOW*.

**Comment by danielsclint** [comment]
I was able to connect with @billyc and @bstabler. They are both in Washington for TRB this week. But, @billyc said he could take care of this on the OMX side starting next week. Is it feasible to hold onto the PR requests until then or would it make more sense to merge the PRs and then make the transition when OMX ready in the next week or two?

**Comment by fscottfoti** [comment]
I'm happy to wait on the updates - just wanted to keep everyone in the loop.  No hurry and enjoy TRB @billyc

**Comment by fscottfoti** [comment]
Finally circling back around to this... any word on the latest on the OMX integration?  Can we help get OMX distributable as a Python package in the usual way (so that we can import it)?

**Comment by danielsclint** [comment]
From an email from @billyc...

I don't remember if you're on the OMX mailing list – see below, PIP installer is done.
- Billy
 
Sent: Thursday, January 15, 2015 1:03 PM
Subject: pip install openmatrix -- Python installer created.
 
I've created a standard pip installer for the python OMX api.  You can now install omx into your python distribution with the following magic command:
 
pip install openmatrix
 
This command will fetch openmatrix from the PyPi repository and download/install it for you.
 
IMPORTANT NOTE!  The package name "omx" was already taken on pip for a lame xml library that no one uses. Thus our little project goes by "openmatrix" on pip instead of "omx". 
 
This means your import statements need to change.  Any occurrence in your code of:
 
   import omx
 
must be changed to:
 
   import openmatrix as omx
 
Other than that I think we're good to go.
..b
 
--

**Comment by fscottfoti** [comment]
Sweet.  @jiffyclub does this all look right to you?  We should start cascading this update in the PRs and start merging...

**Comment by jiffyclub** [comment]
Definitely give it a try. I made some minor changes when I brought omx into activitysim, but I doubt we are relying on them.
